apiVersion: v1
kind: Service
metadata:
  name: hotrod
  labels:
    app: hotrod
spec:
  ports:
    - port: 8080
  selector:
    app: hotrod
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  labels:
    app: hotrod
spec:
  selector:
    matchLabels:
      app: hotrod
      tier: frontend
  template:
    metadata:
      labels:
        app: hotrod
        tier: frontend      
    spec:
      containers:
      - image: jaegertracing/example-hotrod:latest
        name: hotrod
        env:
          - name: JAEGER_AGENT_HOST
            value: simplest-agent.observability.svc.cluster.local
          - name: JAEGER_SERVICE_NAME
            value: hello-service
          - name: JAEGER_AGENT_PORT
            value: "6831"
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://simplest-collector.observability.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "" 
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true" 
        ports:
        - containerPort: 8080
          name: hotrod