apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sample-app
  labels:
    name: my-sample-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sample-app
  template:
    metadata:
      annotations:
        sidecar.jaegertracing.io/inject: "true"
      labels:
        app: my-sample-app
    spec:
      containers:
        - name: my-sample-app
          image: usuelter/sample-app-1
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://simplest-collector.observability.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://simplest-collector.observability.svc.cluster.local:4318" 
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true" 
          ports:
            - name: frontend
              containerPort: 8888
              protocol: TCP