apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: secondtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-sample-app
  labels:
    name: second-sample-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-sample-app
  template:
    metadata:
      annotations:
        sidecar.jaegertracing.io/inject: "true"
      labels:
        app: second-sample-app
    spec:
      containers:
        - name: second-sample-app
          image: usuelter/sample-app-2
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://simplest-collector.observability.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "" 
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true" 
          ports:
            - name: backend-port
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: second-sample-app
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000